### ISSUE TITLE
Can this work with RXTX?

### ISSUE THREAD

**Issue by Dekken** [gythialy/j60870#1]
Hey

Looking at https://www.openmuc.org/index.php?id=72 it gives a small impression that this can be used over serial connections, is this the case? If so, how so?

Thanks

**Comment by gythialy** [comment]
No. IEC 60870-5-104 is a network communication standard.

[This](https://github.com/gythialy/openmuc/blob/cefe3286eebb959d9f46cf7cdf7f921a300f3958/projects/driver/ehz/src/main/java/org/openmuc/framework/driver/ehz/iec62056_21/IecReceiver.java#L78) is the usage of RXTX, and u can download the lib (Java and native) from [here](https://github.com/gythialy/openmuc/tree/cefe3286eebb959d9f46cf7cdf7f921a300f3958/dependencies/rxtx).

**Comment by Dekken** [comment]
I've made a few maven pom files to get the Ehz driver working if you want them.

For rxtx and jdmls aswell.

If I wanted to test an RS232 connection with IEC_60870 would I use the IecConnection or IecReceiver?

**Comment by Dekken** [comment]
or if you a copy of librxtsSerial.so that works on an ARMv7 raspberry pi OOTB.
